config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#index'
  get 'pages', to: 'pages#index'
  get 'simple-show-bulma', to: 'pages#simple_show_bulma'
  get 'lodash_moment_sort', to: 'pages#lodash_moment_sort'
  get 'lodash_only_sort', to: 'pages#lodash_only_sort'
  get 'babel-7-8', to: 'pages#babel_7_8'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController

  def index
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def simple_show_bulma; end

  def lodash_moment_sort; end

  def lodash_only_sort; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  def title(sub_title)
    content_for(:title) { sub_title }
  end

  def description(description)
    content_for(:meta_description) { description }
  end
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns= "http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Language" content="en">

<title>
  <%= if content_for?(:title) then
        yield(:title) + ' | '
      end %>
  rails/webpacker Examples
</title>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<% if yield(:meta_description).present? %>
    <meta name="description" content="<%= yield(:meta_description) %>" />
  <% else %>
    <meta name="description" content="Examples of how to extend and customize rails/webpacker." />
  <% end %>

<meta name="viewport" content="width=device-width, initial-scale=1">
<%= yield :head %>
</head>

<body>
<%= render "shared/navbar" %>
<section class="section">
  <div class="container">
    <%= yield %>
  </div>
</section>
</body>
<%= yield :after_body %>
</html>

app/views/pages/babel_7_8.html.erb
<% content_for :head do %>
  <%= stylesheet_packs_with_chunks_tag("babel-7-8-example") %>
  <%= javascript_packs_with_chunks_tag("babel-7-8-example") %>
<% end %>

<h1 class="title">
  TODO: UPDATE THIS PAGE FOR A NEWER BABEL
  Babel 7.8 Example
</h1>

<h2 class="title">
  Updating to Babel 7.8 from Babel 7.7<br/>
</h2>
<p>
Why update? For the full details, check out this blog post:
</p>
<a href="https://babeljs.io/blog/2020/01/11/7.8.0">
  7.8.0 Released: ECMAScript 2020, .mjs configuration files and @babel/cli improvements
</a>
</p>
<ol>
  <li>
    The nullish coalescing operator, '??', allows you to provide a fallback value when an
    expression
    evaluates to null or undefined.
  </li>
  <li>
    The optional chaining operator, '?.' uses the same concept of 'nullish values', allowing
    optional property accesses on values which could be nullish. It also supports optional
    function
    calls and computed properties.
  </li>
</ol>
<br/>
<br/>

<h2 class="title">
  Example
</h2>
<p>
  Open up the console of your browser. You will see the result of executing some code like the below.
  Note, you can't run these commands in your browser unless your browser supports ECMA 2020

  You can see the source code in <a href="https://github.com/shakacode/webpacker-examples/blob/master/app/javascript/packs/babel-7-8-example.js">app/javascript/packs/babel-7-8-example.js</a>.
</p>

<pre>
  const person = {};

  // Null Coalescing
  const name = person.fullName ?? "Anonymous";
  console.log(`?? operator example: Hello, ${name}!`);

  const element = { index: 0, value: "foo" };
  const index = element.index ?? -1; //  0 :D
  console.log(`?? operator example: index: ${index}.`);

  const indexUsingOr = element.index || -1; // -1 :(
  console.log(`Compared to || operator example: indexUsingOr: ${indexUsingOr}.`);

  const city = person.address?.city; // person.address could be not defined
  const isNeighbor = person.address?.isCloseTo(me);
  const sayingHay = person.sayHayUsing?.("Twitter"); // The person.sayHayUsing method could be not defined

  console.log(`city = ${city}, isNeighbor = ${isNeighbor}, sayingHay = ${sayingHay}`);
  </pre>
<br/>
<br/>
<h2 class="title">
  Your console will show:
</h2>

<pre>
  babel-7-8-example.js:6 ?? operator example: Hello, Anonymous!
  ?? operator example: index: 0.
  Compared to || operator example: indexUsingOr: -1.
  city = undefined, isNeighbor = undefined, sayingHay = undefined
</pre>

app/views/pages/index.erb
<% content_for :head do%>
  <%= stylesheet_pack_tag("sort") %>
  <%= javascript_pack_tag("sort") %>
<% end %>

<ul>
  <li>
    <%= link_to "Script loaded in HEAD", "sort" %>
  </li>
  <li>
    <%= link_to "Script loaded after body", "sort-backwards" %>
  </li>
</ul>

app/views/pages/index.html.erb
<% content_for :head do%>
  <%= stylesheet_packs_with_chunks_tag("home") %>
  <%= javascript_packs_with_chunks_tag("home") %>
<% end %>

<h1 class="title">
  rails/Webpacker examples
</h1>

Source code on Github at <a href="https://github.com/shakacode/webpacker-examples">shakacode/webpacker-examples</a>

app/views/pages/lodash_moment_sort.html.erb
<% content_for :head do%>
  <%= stylesheet_packs_with_chunks_tag("lodash-moment-sort") %>
  <%= javascript_packs_with_chunks_tag("lodash-moment-sort") %>
<% end %>

<% title "Code Splitting, Script loaded in HEAD, with both Lodash and Moment" %>
<% description "Code Splitting, Script loaded in HEAD, with both Lodash and Moment, demonstrating why code-splitting is necessary with @rails/webpacker." %>

<h1>Code Splitting, Script loaded in HEAD, with both Lodash and Moment</h1>

<form id="number-form">
  <h1>MAGIC SORTER using Lodash</h1>
  <div class="inputs">
    <input id="input1" class="input-number" type="number" value="33" />
    <input id="input2" class="input-number" type="number" value="1" />
    <input id="input3" class="input-number" type="number" value="99" />
  </div>
  <button>
    Click to sort your numbers.
  </button>
  <div id="results">
  </div>
</form>
<hr/>
<form id="date-form">
  <h1>Date Parser using Moment.js</h1>
  <div class="inputs">
    <input id="inputDate" class="input-date" type="string" value="" />
  </div>
  <button>
    Click to parse your date
  </button>
  <div id="resultsDate">
  </div>
</form>
<hr/>
<p>
  This screen uses 2 large JavaScript libraries, Lodash and Moment.
</p>

app/views/pages/lodash_only_sort.html.erb
<% content_for :head do%>
  <%= stylesheet_packs_with_chunks_tag("lodash-only-sort") %>
<% end %>

<% content_for :after_body do%>
  <%= javascript_packs_with_chunks_tag("lodash-only-sort") %>
<% end %>

<% title "Code Splitting, Script loaded after BODY, using only Lodash" %>
<% description "Code Splitting, Script loaded in HEAD, with only Lodash, demonstrating how JavaScript can be loaded after the HTML with @rails/webpacker." %>

<h1>Code Splitting, Script loaded after BODY, using only Lodash</h1>

<form id="form">
  <h1>MAGIC SORTER BACKWARDS using Lodash</h1>
  <div class="inputs">
    <input id="input1" type="number" value="33" />
    <input id="input2" type="number" value="1" />
    <input id="input3" type="number" value="99" />
  </div>
  <button>
    Click to sort your numbers BACKWARDS.
  </button>
  <div id="results">

  </div>
</form>

app/views/pages/simple_html.html.erb
<% content_for :head do %>
  <%= stylesheet_packs_with_chunks_tag("application") %>
  <%= javascript_packs_with_chunks_tag("application") %>
<% end %>

<% title "Bulma CSS Framework Example Page" %>
<% description "Bulma CSS Framework Example Page demonstrating Bulma CSS integration with @rails/webpacker." %>

<h1 class="title">
  Bulma CSS Framework Example Page
</h1>

<p class="subtitle">
  <a href="https://bulma.io/">Bulma</a> is a modern CSS framework based on
  <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox">Flexbox</a>
</p>

<div class="field">
  <div class="control">
    <input class="input" type="text" placeholder="Input">
  </div>
</div>

<div class="field">
  <p class="control">
      <span class="select">
        <select>
          <option>Select dropdown 1</option>
          <option>Select dropdown 2</option>
          <option>Select dropdown 3</option>
        </select>
      </span>
  </p>
</div>

<div class="buttons">
  <a class="button is-primary">Primary</a>
  <a class="button is-link">Link</a>
</div>

app/views/pages/simple_show_bulma.html.erb
<% content_for :head do %>
  <%= stylesheet_packs_with_chunks_tag("simple-show-bulma") %>
  <%= javascript_packs_with_chunks_tag("simple-show-bulma") %>
<% end %>

<% title "Bulma CSS Framework Example Page" %>
<% description "Bulma CSS Framework Example Page demonstrating Bulma CSS integration with @rails/webpacker." %>

<h1 class="title">
  Bulma CSS Framework Example Page
</h1>

<p class="subtitle">
  <a href="https://bulma.io/">Bulma</a> is a modern CSS framework based on
  <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox">Flexbox</a>
</p>

<div class="field">
  <div class="control">
    <input class="input" type="text" placeholder="Input">
  </div>
</div>

<div class="field">
  <p class="control">
      <span class="select">
        <select>
          <option>Select dropdown 1</option>
          <option>Select dropdown 2</option>
          <option>Select dropdown 3</option>
        </select>
      </span>
  </p>
</div>

<div class="buttons">
  <a class="button is-primary">Primary</a>
  <a class="button is-link">Link</a>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://www.shakacode.com">
      <img src="<%= asset_pack_path 'media/images/Logo.png' %>"/>
    </a>
    <a class="navbar-item" href="https://www.shakacode.com">
      <strong>ShakaCode</strong>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="/">
        Home
      </a>

      <%= link_to "Bulma", simple_show_bulma_path, class: "navbar-item" %>
      <%= link_to "lodash only", lodash_only_sort_path, class: "navbar-item" %>
      <%= link_to "lodash and moment", lodash_moment_sort_path, class: "navbar-item" %>
      <%= link_to "Babel 7.8", babel_7_8_path, class: "navbar-item" %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a href="https://www.shakacode.com/about"class="navbar-item">
            About
          </a>
          <hr class="navbar-divider">
          <a href="https://github.com/shakacode/webpacker-examples" class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary" href="https://www.shakacode.com/recent-work">
            <strong>ShakaCode Recent Work</strong>
          </a>
          <a class="button is-light"
             href="https://github.com/shakacode/webpacker-examples" >
            Github
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/sort/index.html.erb
<% content_for :head do%>
  <%= stylesheet_packs_with_chunks_tag("sort") %>
  <%= javascript_packs_with_chunks_tag("sort") %>
<% end %>

<% title "Code Splitting, Script loaded in HEAD, with both Lodash and Moment" %>
<% description "Code Splitting, Script loaded in HEAD, with both Lodash and Moment, demonstrating why code-splitting is necessary with @rails/webpacker." %>

<h1>Code Splitting, Script loaded in HEAD, with both Lodash and Moment</h1>

<form id="number-form">
  <h1>MAGIC SORTER using Lodash</h1>
  <div class="inputs">
    <input id="input1" class="input-number" type="number" value="33" />
    <input id="input2" class="input-number" type="number" value="1" />
    <input id="input3" class="input-number" type="number" value="99" />
  </div>
  <button>
    Click to sort your numbers.
  </button>
  <div id="results">
  </div>
</form>
<hr/>
<form id="date-form">
  <h1>Date Parser using Moment.js</h1>
  <div class="inputs">
    <input id="inputDate" class="input-date" type="string" value="" />
  </div>
  <button>
    Click to parse your date
  </button>
  <div id="resultsDate">
  </div>
</form>
<hr/>
<p>
  This screen uses 2 large JavaScript libraries, Lodash and Moment.
</p>

app/views/sort_backwards/index.html.erb
<% content_for :head do%>
  <%= stylesheet_packs_with_chunks_tag("sort-backwards") %>
<% end %>

<% content_for :after_body do%>
  <%= javascript_packs_with_chunks_tag("sort-backwards") %>
<% end %>

<% title "Code Splitting, Script loaded after BODY, using only Lodash" %>
<% description "Code Splitting, Script loaded in HEAD, with both Lodash and Moment, demonstrating how JavaScript can be loaded after the HTML with @rails/webpacker." %>

<h1>Code Splitting, Script loaded after BODY, using only Lodash</h1>

<form id="form">
  <h1>MAGIC SORTER BACKWARDS using Lodash</h1>
  <div class="inputs">
    <input id="input1" type="number" value="33" />
    <input id="input2" type="number" value="1" />
    <input id="input3" type="number" value="99" />
  </div>
  <button>
    Click to sort your numbers BACKWARDS.
  </button>
  <div id="results">

  </div>
</form>